### PR TITLE
Specify encoding as utf-8

### LINKED ISSUE #9: 'ascii' codec can't decode byte in Some Snapeda v6 files
Hi, importing of Some of my Snapeda v6 files failes with an ascii codec error.
The relevant files are:
 - https://www.snapeda.com/parts/150060RS75000/Wurth+Elektronik/view-part/
 - https://www.snapeda.com/parts/AZ1117CH-3.3TRG1/Diodes+Inc./view-part/
 - https://www.snapeda.com/parts/C2012X7R1E105M085AB/TDK/view-part/
 - https://www.snapeda.com/parts/GRM188R61E475KE11D/Murata+Electronics+North+America/view-part/
 - https://www.snapeda.com/parts/SFR10EZPJ101/Rohm/view-part/

here the detailed import protocol:
```
Import: /home/user/Downloads/kicad/06033C104KAT2A.zip
Identify Snapeda
Import of kicad_sym skipped
Import of 3d model skipped
Import of footprint skipped
OK

Import: /home/user/Downloads/kicad/150060RS75000.zip
Identify Snapeda
'ascii' codec can't decode byte 0xc3 in position 882: ordinal not in range(128)

Import: /home/user/Downloads/kicad/AZ1117CH-3.3TRG1.zip
Identify Snapeda
'ascii' codec can't decode byte 0xc2 in position 1737: ordinal not in range(128)

Import: /home/user/Downloads/kicad/BFP650FH6327XTSA1.zip
Identify Snapeda
Import of kicad_sym skipped
Import of 3d model skipped
Import of footprint skipped
OK

Import: /home/user/Downloads/kicad/C2012X7R1E105M085AB.zip
Identify Snapeda
'ascii' codec can't decode byte 0xc2 in position 756: ordinal not in range(128)

Import: /home/user/Downloads/kicad/CRCW080520K0FKEA.zip
Identify Snapeda
Import of kicad_sym skipped
Import of 3d model skipped
Import of footprint skipped
OK

Import: /home/user/Downloads/kicad/CRCW08054K70FKEA.zip
Identify Snapeda
Import of kicad_sym skipped
Import of 3d model skipped
Import of footprint skipped
OK

Import: /home/user/Downloads/kicad/GRM188R61E475KE11D.zip
Identify Snapeda
'ascii' codec can't decode byte 0xc2 in position 2254: ordinal not in range(128)

Import: /home/user/Downloads/kicad/ICM-42688-P.zip
Identify Snapeda
Import of kicad_sym skipped
Import of 3d model skipped
Import of footprint skipped
OK

Import: /home/user/Downloads/kicad/SFR10EZPJ101.zip
Identify Snapeda
'ascii' codec can't decode byte 0xc2 in position 722: ordinal not in range(128)

Import: /home/user/Downloads/kicad/TL3305BF260QG.zip
Identify Snapeda
Import of kicad_sym skipped
Import of 3d model skipped
Import of footprint skipped
OK


##############################

Important information: 
If you have already used the previous version of the plugin, you should note that the current version supports all library files. Files with the new format are imported as *_kicad_sym and must be included in the settings (only Symbol Lib). The settings are checked at the end of the import process.

KICAD_3RD_PARTY is not defined in Environment Variables.

More information can be found in the README for the integration into KiCad.
github.com/Steffen-W/Import-LIB-KiCad-Plugin
Some configurations require a kicad restart to be detected correctly.

##############################

```

### PR DESCRIPTION
**Pull request by 42CrMo4**
closes #9 

Open a file or read text in utf-8 encoding.

### CODE REVIEW

**Comment by Steffen-W** [comment]
Thank you for your efforts @42CrMo4 .

**Comment by 42CrMo4** [comment]
You are welcome.

**Comment by 42CrMo4** [comment]
@Steffen-W would you mind updating the Kicad Addon repo with the new version?

**Comment by Steffen-W** [comment]
Hi @42CrMo4,

I have placed a [merge_requests](https://gitlab.com/kicad/addons/metadata/-/merge_requests/304). In about 3-5 days it should be available as a new version in KiCad.

**Comment by 42CrMo4** [comment]
Thank you very much, also for this very nice and timesaving Addon.

**Pull request merged**
