### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by udu3324**
I have reformatted some stuff, added badges, and made the installation process more clear

### CODE REVIEW

**Comment by Steffen-W** [comment]
@udu3324 Many thanks for your pull request. I will add it as soon as possible. Give me some time. Maybe I'll manage to make the plugin more comfortable so that some of the instructions are no longer absolutely necessary. What is your opinion if I make a button in the plugin with which the setting of kicad is made in the background?

This "_kicad_sym.kicad_sym" is really unattractive, which you must have noticed negatively. Unfortunately, I have not yet implemented the solution, so this name is unnecessary. I am working on it.

**Comment by udu3324** [comment]
> What is your opinion if I make a button in the plugin with which the setting of kicad is made in the background?
I think that would be awesome. KiCad might have an api that can do that

**Comment by Steffen-W** [comment]
As far as I know, KiCad does not have direct access to it, which is a pity. But I can change the config files directly. The disadvantage is that a restart is necessary to read in the config files. I had already prepared something for this a long time ago, but unfortunately did not continue due to time constraints.
[impart_helper_func.py#L84](https://github.com/Steffen-W/Import-LIB-KiCad-Plugin/blob/213a68f22e234927548cb7696d20632b7a879111/plugins/impart_helper_func.py#L84)

**Comment by udu3324** [comment]
I also found this [forum post](https://forum.kicad.info/t/how-to-read-configured-paths-from-python/39664) showing how to get paths. It is through `pcbnew` and could simplify the ui.
image

I would love to try contributing more, but i am not sure how to setup a dev environment

**Comment by Steffen-W** [comment]
Hi @udu3324 ,

It is not necessary to create a separate environment. You can simply change the plugin at the installed location and output to the terminal, provided you start kicad from there. Which platform are you using?

**Comment by udu3324** [comment]
@Steffen-W I am running KiCad on Windows 11. If that is the case though, i will go ahead and try to add some stuff to the plugin.

**Comment by Steffen-W** [comment]
It is best to use PowerShell and go to the KiCad directory on your pc.
```
PS C:\ ......\KiCad\8.0\bin> .\kicad.exe
```
You can find out the plugin directory in the plugin manager. You can then make the changes in the Python files. use print() to output this to the console. Try it and write if it does not work. As a rule, the python files are also reloaded if you only close and reopen the PCB viewer.

**Comment by Steffen-W** [comment]
@udu3324 ,
I have added the option of automatic KiCad settings customization. If you like, have a look at it and please give me feedback. [tag/2024.08.03](https://github.com/Steffen-W/Import-LIB-KiCad-Plugin/releases/tag/2024.08.03)

**Pull request closed without merging**
